JuliaGeodynamics/GeophysicalModelGenerator.jl

src/GeophysicalModelGenerator.jl
src/LaMEM_io.jl
src/Setup_geometry.jl
src/data_types.jl
src/utils.jl
test/runtests.jl
test/test_lamem.jl
test/test_setup_geometry.jl

This introduces the `CartGrid` struct; an orthogonal Cartesian grid object which can be used in numerical codes and contains 1D vectors that give the coordinates in the 1D/2D/3D directions. 
You can generate a grid with:
```julia
julia> Grid      =   CreateCartGrid(size=(10,20,30),x=(0.,10), y=(0.,10), z=(2.,10))
julia> Temp    =   ones(Float64, Grid.N...)*1350;
julia> Phases =   zeros(Int32,  Grid.N...);
```
This allows you to set properties in the usual manner:
```julia
julia> AddBox!(Phases,Temp,Grid, xlim=(2,4), zlim=(-15,-10), phase=ConstantPhase(3), DipAngle=10, T=LinearTemp(Tbot=1350, Ttop=200))
```
Once this is generated, you can create a `CartData` structure from it with
```julia
julia> Data = CartData(Grid, (T=Temp, Phases=Phases))
```
Or, ofcourse, use `Temp`,`Phases` in …

Cartesian Grids

---

Project.toml
src/LaMEM_io.jl
test/test_files/Subduction_VEP.dat
test/test_lamem.jl

Previously, LaMEM files with grid refinement would only work if the refinement was done in all 3 directions; now it allows works if only 1 or 2 directions are refined.

LaMEM Grid refinement in <3 directions

---

.github/workflows/blank.yml

[GMT.jl](https://github.com/GenericMappingTools/GMT.jl) now has version 1.0 which uses `GMT_jll` (=precompiled binaries) by default. That makes it easier to use and as such we can add it as a direct dependency rather than as an optional one.
Yet, the issue is that it no longer works with Julia 1.7, but requires 1.8 & 1.9. Nightly is currently broken as well, but that is perhaps fixed before 1.10 is released. 
See the [discussion](https://github.com/GenericMappingTools/GMT.jl/issues/447) about `GMT_jll`.
Shall we increase the minimum required Julia version to >1.7 for `GMG` (and remove nightly from testing)?

Upgrade GMT dependency

---

Project.toml
src/utils.jl
test/test_utils.jl

This enhances the way we can manipulate vertical cross-sections through 3D datasets. It allows you to project data onto a higher resolution area along a 2D cross-section taken through a 3D dataset.
Let's start with a vertical cross-section:
```Julia
julia> X,Y,Z = XYZGrid(10:20,30:40,-300:25:0);
julia> Data = Z.*2
julia> Data_Int = Int64.(Data)
julia> DataSet_Cart = CartData(X,Y,Z,(Data=Data,Data_Int=Data_Int, Velocity=(X,Y,Z)))
julia> Data_cross = CrossSection(DataSet_Cart, Start=(11.0,35), End=(19, 39.0))
CartData 
size    : (100, 100, 1)
x       ϵ [ 11.0 : 19.0]
y       ϵ [ 35.0 : 39.0]
z       ϵ [ -300.0 : 0.0]
fields  : (:Data, :Data_Int, :Velocity, :FlatCrossSection)
attributes: ["note"]
```
Note that this cross-section contains the field `FlatCrossSection`, which contains the …

Extend cross-section routines

---

Project.toml
src/data_import.jl
test/test_data_import.jl

This allows you to specify a fieldname that is different from `:colors` when importing a Screenshot:
```Julia
julia> data_Image_newfieldname  =   Screenshot_To_GeoData(filename,Corner_LowerLeft, Corner_UpperRight, fieldname=:fake)
Extracting GeoData from: test.png
└ Corners:         lon       lat       depth
└ lower left  = (18.0   , 51.0   ,  -590.0 )
└ lower right = (9.0    , 42.0   ,  -590.0 )
└ upper left  = (18.0   , 51.0   ,  0.0    )
└ upper right = (9.0    , 42.0   ,  0.0    )
GeoData 
size      : (100, 200, 1)
lon       ϵ [ 18.0 : 9.0]
lat       ϵ [ 51.0 : 42.0]
depth     ϵ [ 0.0 : -590.0]
fields    : (:fake,)
attributes: ["note"]
```

Allow specifying a fieldname when importing screenshots

---

src/IO.jl
test/test_IO.jl

This adds a function that downloads remote data. This is mostly helpful to make the tutorials more reproducible

Download remote data 

---

.typos.toml

This adds `*.pvsm` files to the ignore list to avoid problems like in https://github.com/JuliaGeodynamics/GeophysicalModelGenerator.jl/actions/runs/8099469655/job/22135274742

Update and rename _typos.toml to .typos.toml

---

src/utils.jl
test/test_utils.jl

Added inpolygon function which is needed for the setup generation of Tatjana/Andrea

Added inPolygon with tests

---

docs/make.jl
docs/src/man/paraview_collection.md
src/GeophysicalModelGenerator.jl
src/Paraview_collection.jl
test/runtests.jl
test/test_paraview_collection.jl

This adds a routine for generating a `.pvd` file from existing `.vtk` files. This is especially useful if a model did not store a `paraview collection` or stopped before the assigned end of the simulation
```julia
make_paraview_collection(; dir=pwd(), pvd_name=nothing, files=nothing, file_extension = ".vts", time = nothing)
In case one has a list of `*.vtk` files, this routine creates a `*.pvd` file that can be opened in Paraview.
This is useful if you previously saved vtk files but didnt save it as a collection in the code itself.
Optional options
===
- `dir`:    directory where the `*.vtk` are stored.
- `pvd_name`:  filename of the resulting `*.pvd` file without extension; if not specified, `full_simulation` is used.
- `files`:  Vector of the `*.vtk` files without extension; if not …
```

Paraview collection 

---

docs/src/man/geodynamic_setups.md
src/Setup_geometry.jl
test/test_setup_geometry.jl

This PR adds two features:
_1) Slab-internal thermal structure of a slab within the mantle_
This follows McKenzie (1969) in computing a thermal structure within a slab:
```Julia
x       = LinRange(0.0,1200.0,64);
y       = LinRange(0.0,1200.0,64);
z       = LinRange(-660,50,64);
Cart    = CartData(XYZGrid(x, y, z));
Phase   = ones(Int32,size(Cart));
Temp    = ones(Float64,size(Cart))*1350;
TsMK = McKenzie_subducting_slab(Tsurface = 20.0, Tmantle = 1350.0, v_cm_yr = 4.0, Adiabat = 0.0)
Temp    = ones(Float64,size(Cart))*1350;
AddBox!(Phase, Temp, Cart; xlim=(0.0,600.0),ylim=(0.0,600.0), zlim=(-80.0,0),StrikeAngle=0, DipAngle=45, phase = ConstantPhase(5), T=TsMK);
```
_2) Averaging temperature along a slab between two end member profiles_
This allows a linear transition between two …

Slab-internal temperature and linear thermal averaging

---

ext/GMT_utils.jl
src/IO.jl

The CI frequently fails because of problems with downloading remote data. This PR makes several download attempts before giving up, with the hope to reduce this issue. We also delete the local download file from disk once data is downloaded and imported using `load_GMG` with a remote dataset

Multiple download attempts for remote data

---

docs/src/man/geodynamic_setups.md
src/Setup_geometry.jl
test/test_setup_geometry.jl

This pull request adds `addStripes!` function. 
This simple function allow to add stripes on existing phase to facilitate strain visualization when running forward LaMEM models.
The function takes as arguments
1. a tuple of axes to activate the stripes in x,y and z dimensions
2. a stripe width
3. a stripe spacing
4. Origin, StrikeAngle and DipAngle to apply rotation
5. a reference phase for which the striping will be applied
6. a stripe phase
And example of `addStripes!`:
```
using GeophysicalModelGenerator
Grid = ReadLaMEM_InputFile("test/test_files/SaltModels.dat")
Phases = zeros(Int32,   size(Grid.X));
Temp   = zeros(Float64, size(Grid.X));
AddBox!(Phases,Temp,Grid, xlim=(0,500), zlim=(-50,0), phase=ConstantPhase(3), DipAngle=10, T=ConstantTemp(1000))
addStripes!(Phases, Grid, …
```

Function to add stripes on shapes

---

src/data_types.jl

Quick fix to make `ProjectionPoint`  type stable. `Int` is an abstract type, while `Int64` is concrete.

Make `ProjectionPoint` type stable

---

src/ProfileProcessing.jl

If no point data was present around a profile, this resulted in an error with flatten_cross_section, as it could not handle the type "Nothing". I fixed this by checking if the output argument of cross_section_points does contain data before proceeding.

fix bug in ProfileProcessing.jl

---

docs/src/man/Tutorial_AlpineData.md
docs/src/man/Tutorial_Jura.md
docs/src/man/Tutorial_LaPalma.md
docs/src/man/tutorial_GMT_Topography.md
docs/src/man/tutorial_GMT_Topography_GeologicalMap.md
docs/src/man/tutorial_GPS.md
ext/GMT_utils.jl

The issue was the `.grd` extension in the file name. It should be 
```julia
Topo = import_topo([14,15, 37, 38], file="@earth_relief_01m")
```
instead of 
```julia
Topo = import_topo([14,15, 37, 38], file="@earth_relief_01m.grd")
```
This also fixes the CI.

Fix the download of topographyic data with GMT

---

docs/src/man/tutorial_GMT_Topography.md

Attempts to fix the rendering of the GMT database table in `Tutorial 5`

Fix table rendering

---

src/sea_lvl.jl
test/test_utils.jl

This fixes issue #132 and adds a test for surface interpolation when 2 surfaces are `GeoData` grids

Bugfixes for sealevel and test for GeoData surface interpolation

---

src/utils.jl
test/test_utils.jl

This PR fixes `cross_section_surface` to export the correct `AbstractGeneralGrid` type rather than only `GeoData`: 
```julia
if isa(S,GeoData)
Data_profile = GeoData(Lon, Lat, depth_intp, fields_new);
elseif isa(S,CartData)
Data_profile = CartData(Lon, Lat, depth_intp, fields_new);
else
error("still to be implemented")
end
```

fix GeoData export

---

Project.toml
src/Setup_geometry.jl

This fixes an issue with MPI setups that was noticed when building a subducting slab setup on multiple processors. 
The issue arose because the code was trying to compute the temperature at the processor boundary and failed as it returned an empty vector. This occurs when a geometry object was set with `add_box!` or `add_sphere`, but the coordinates of the object were completely outside the range of the current box.
Previous setup on 1 MPi rank:
and with 2 ranks
and with the fix in this PR:

MPI fix of temperature computation

---

src/Setup_geometry.jl
test/runtests.jl
test/test_plate.jl

This pull request introduces a new function, add_plate, to create tectonic plates based on xy coordinates. This function builds upon the existing functionality of add_polygon, but is specifically adapted for defining tectonic plates with complex geometries and properties. The user can input multiple coordinates in the x and y directions to define the plate's geometry, while specifying a single tuple in the z direction to determine the depth range of the plate.
Additionally, this new function integrates the recently introduced functionality for segmented ridges, allowing plates to incorporate ridge structures. The add_plate function now accepts the temperature calculations from the ridge structure, enabling more accurate thermal and phase modeling for tectonic plates.

New function for generating tectonic plates with custom geometries and constant depth

---

src/Setup_geometry.jl

This PR adds the missing condition to define `T = nothing` in the `add_volcano` function. This can be useful if one wants to add e.g. a few layers in a volcano. 
```julia
if !isnothing(T)
Temp[ind_flat] = compute_thermal_structure(Temp[ind_flat], Grid.x.val[ind], Grid.y.val[ind], depth[ind], Phases[ind_flat], T)
end
```

add condition if `T=nothing`
